# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import services.eth_node_mock.proto.streamer_pb2 as streamer__pb2


class NodeCommuunicationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ServiceInfo = channel.unary_unary(
        '/eth.NodeCommuunications/ServiceInfo',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.ServiceVersion.FromString,
        )
    self.EventGetGasPrice = channel.unary_unary(
        '/eth.NodeCommuunications/EventGetGasPrice',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.GasPrice.FromString,
        )
    self.EventInitialAdd = channel.unary_unary(
        '/eth.NodeCommuunications/EventInitialAdd',
        request_serializer=streamer__pb2.UsersData.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.EventAddNewAddress = channel.unary_unary(
        '/eth.NodeCommuunications/EventAddNewAddress',
        request_serializer=streamer__pb2.WatchAddress.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.EventAddNewMultisig = channel.unary_unary(
        '/eth.NodeCommuunications/EventAddNewMultisig',
        request_serializer=streamer__pb2.WatchAddress.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.EventGetBlockHeight = channel.unary_unary(
        '/eth.NodeCommuunications/EventGetBlockHeight',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.BlockHeight.FromString,
        )
    self.EventGetCode = channel.unary_unary(
        '/eth.NodeCommuunications/EventGetCode',
        request_serializer=streamer__pb2.AddressToResync.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.EventGetAdressNonce = channel.unary_unary(
        '/eth.NodeCommuunications/EventGetAdressNonce',
        request_serializer=streamer__pb2.AddressToResync.SerializeToString,
        response_deserializer=streamer__pb2.Nonce.FromString,
        )
    self.EventGetAdressBalance = channel.unary_unary(
        '/eth.NodeCommuunications/EventGetAdressBalance',
        request_serializer=streamer__pb2.AddressToResync.SerializeToString,
        response_deserializer=streamer__pb2.Balance.FromString,
        )
    self.EventGetAllMempool = channel.unary_stream(
        '/eth.NodeCommuunications/EventGetAllMempool',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.MempoolRecord.FromString,
        )
    self.EventAddMempoolRecord = channel.unary_stream(
        '/eth.NodeCommuunications/EventAddMempoolRecord',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.MempoolRecord.FromString,
        )
    self.EventDeleteMempool = channel.unary_stream(
        '/eth.NodeCommuunications/EventDeleteMempool',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.MempoolToDelete.FromString,
        )
    self.EventResyncAddress = channel.unary_unary(
        '/eth.NodeCommuunications/EventResyncAddress',
        request_serializer=streamer__pb2.AddressToResync.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.EventNewBlock = channel.unary_stream(
        '/eth.NodeCommuunications/EventNewBlock',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.BlockHeight.FromString,
        )
    self.CheckRejectTxs = channel.unary_unary(
        '/eth.NodeCommuunications/CheckRejectTxs',
        request_serializer=streamer__pb2.TxsToCheck.SerializeToString,
        response_deserializer=streamer__pb2.RejectedTxs.FromString,
        )
    self.EventSendRawTx = channel.unary_unary(
        '/eth.NodeCommuunications/EventSendRawTx',
        request_serializer=streamer__pb2.RawTx.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.NewTx = channel.unary_stream(
        '/eth.NodeCommuunications/NewTx',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.ETHTransaction.FromString,
        )
    self.SyncState = channel.unary_unary(
        '/eth.NodeCommuunications/SyncState',
        request_serializer=streamer__pb2.BlockHeight.SerializeToString,
        response_deserializer=streamer__pb2.ReplyInfo.FromString,
        )
    self.AddMultisig = channel.unary_stream(
        '/eth.NodeCommuunications/AddMultisig',
        request_serializer=streamer__pb2.Empty.SerializeToString,
        response_deserializer=streamer__pb2.Multisig.FromString,
        )
    self.GetMultisigInfo = channel.unary_unary(
        '/eth.NodeCommuunications/GetMultisigInfo',
        request_serializer=streamer__pb2.AddressToResync.SerializeToString,
        response_deserializer=streamer__pb2.ContractInfo.FromString,
        )
    self.GetERC20Info = channel.unary_unary(
        '/eth.NodeCommuunications/GetERC20Info',
        request_serializer=streamer__pb2.ERC20Address.SerializeToString,
        response_deserializer=streamer__pb2.ERC20Info.FromString,
        )


class NodeCommuunicationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ServiceInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventGetGasPrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventInitialAdd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventAddNewAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventAddNewMultisig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventGetBlockHeight(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventGetCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventGetAdressNonce(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventGetAdressBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventGetAllMempool(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventAddMempoolRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventDeleteMempool(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventResyncAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventNewBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckRejectTxs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EventSendRawTx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewTx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMultisig(self, request, context):
    """Multisig methods
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMultisigInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetERC20Info(self, request, context):
    """erc20 methods
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NodeCommuunicationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ServiceInfo': grpc.unary_unary_rpc_method_handler(
          servicer.ServiceInfo,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.ServiceVersion.SerializeToString,
      ),
      'EventGetGasPrice': grpc.unary_unary_rpc_method_handler(
          servicer.EventGetGasPrice,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.GasPrice.SerializeToString,
      ),
      'EventInitialAdd': grpc.unary_unary_rpc_method_handler(
          servicer.EventInitialAdd,
          request_deserializer=streamer__pb2.UsersData.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'EventAddNewAddress': grpc.unary_unary_rpc_method_handler(
          servicer.EventAddNewAddress,
          request_deserializer=streamer__pb2.WatchAddress.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'EventAddNewMultisig': grpc.unary_unary_rpc_method_handler(
          servicer.EventAddNewMultisig,
          request_deserializer=streamer__pb2.WatchAddress.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'EventGetBlockHeight': grpc.unary_unary_rpc_method_handler(
          servicer.EventGetBlockHeight,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.BlockHeight.SerializeToString,
      ),
      'EventGetCode': grpc.unary_unary_rpc_method_handler(
          servicer.EventGetCode,
          request_deserializer=streamer__pb2.AddressToResync.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'EventGetAdressNonce': grpc.unary_unary_rpc_method_handler(
          servicer.EventGetAdressNonce,
          request_deserializer=streamer__pb2.AddressToResync.FromString,
          response_serializer=streamer__pb2.Nonce.SerializeToString,
      ),
      'EventGetAdressBalance': grpc.unary_unary_rpc_method_handler(
          servicer.EventGetAdressBalance,
          request_deserializer=streamer__pb2.AddressToResync.FromString,
          response_serializer=streamer__pb2.Balance.SerializeToString,
      ),
      'EventGetAllMempool': grpc.unary_stream_rpc_method_handler(
          servicer.EventGetAllMempool,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.MempoolRecord.SerializeToString,
      ),
      'EventAddMempoolRecord': grpc.unary_stream_rpc_method_handler(
          servicer.EventAddMempoolRecord,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.MempoolRecord.SerializeToString,
      ),
      'EventDeleteMempool': grpc.unary_stream_rpc_method_handler(
          servicer.EventDeleteMempool,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.MempoolToDelete.SerializeToString,
      ),
      'EventResyncAddress': grpc.unary_unary_rpc_method_handler(
          servicer.EventResyncAddress,
          request_deserializer=streamer__pb2.AddressToResync.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'EventNewBlock': grpc.unary_stream_rpc_method_handler(
          servicer.EventNewBlock,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.BlockHeight.SerializeToString,
      ),
      'CheckRejectTxs': grpc.unary_unary_rpc_method_handler(
          servicer.CheckRejectTxs,
          request_deserializer=streamer__pb2.TxsToCheck.FromString,
          response_serializer=streamer__pb2.RejectedTxs.SerializeToString,
      ),
      'EventSendRawTx': grpc.unary_unary_rpc_method_handler(
          servicer.EventSendRawTx,
          request_deserializer=streamer__pb2.RawTx.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'NewTx': grpc.unary_stream_rpc_method_handler(
          servicer.NewTx,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.ETHTransaction.SerializeToString,
      ),
      'SyncState': grpc.unary_unary_rpc_method_handler(
          servicer.SyncState,
          request_deserializer=streamer__pb2.BlockHeight.FromString,
          response_serializer=streamer__pb2.ReplyInfo.SerializeToString,
      ),
      'AddMultisig': grpc.unary_stream_rpc_method_handler(
          servicer.AddMultisig,
          request_deserializer=streamer__pb2.Empty.FromString,
          response_serializer=streamer__pb2.Multisig.SerializeToString,
      ),
      'GetMultisigInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetMultisigInfo,
          request_deserializer=streamer__pb2.AddressToResync.FromString,
          response_serializer=streamer__pb2.ContractInfo.SerializeToString,
      ),
      'GetERC20Info': grpc.unary_unary_rpc_method_handler(
          servicer.GetERC20Info,
          request_deserializer=streamer__pb2.ERC20Address.FromString,
          response_serializer=streamer__pb2.ERC20Info.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'eth.NodeCommuunications', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
